### ISSUE TITLE
How to build with the latest TI 8.32 SDK

### ISSUE THREAD

**Issue by knyghtryda** [ratsark/oepl-cc2630-firmware#3]
How were you guys able to build with the latest sdk against the cc26x1 device?  No matter what I tried to modify in the Makefile I was always getting errors.  I finally got stuck at the linker step with this error:

```
LD build/Tag_FW_CC2630_TG-GR6000N.elf
/usr/lib/gcc/arm-none-eabi/13.2.1/../../../arm-none-eabi/bin/ld: build/firmware/rtt.o: in function `uart_init':
/home/yhong/oepl-cc2630-firmware/firmware/rtt.c:80:(.text.rtt_init+0x12): undefined reference to `PRCMPowerDomainStatus'
/usr/lib/gcc/arm-none-eabi/13.2.1/../../../arm-none-eabi/bin/ld: build/firmware/oepl_rf_cc2630.o: in function `rf_send_cmd':
/home/yhong/oepl-cc2630-firmware/firmware/oepl_rf_cc2630.c:90:(.text.rf_send_cmd+0x2): undefined reference to `NOROM_RFCDoorbellSendTo'
/usr/lib/gcc/arm-none-eabi/13.2.1/../../../arm-none-eabi/bin/ld: build/firmware/oepl_rf_cc2630.o: in function `oepl_rf_init':
/home/yhong/oepl-cc2630-firmware/firmware/oepl_rf_cc2630.c:147:(.text.oepl_rf_init+0x58): undefined reference to `PRCMPowerDomainStatus'
/usr/lib/gcc/arm-none-eabi/13.2.1/../../../arm-none-eabi/bin/ld: /home/yhong/oepl-cc2630-firmware/firmware/oepl_rf_cc2630.c:157:(.text.oepl_rf_init+0x84): undefined reference to `PRCMPowerDomainStatus'
/usr/lib/gcc/arm-none-eabi/13.2.1/../../../arm-none-eabi/bin/ld: /home/yhong/oepl-cc2630-firmware/firmware/oepl_rf_cc2630.c:160:(.text.oepl_rf_init+0x8e): undefined reference to `PRCMPowerDomainStatus'
/usr/lib/gcc/arm-none-eabi/13.2.1/../../../arm-none-eabi/bin/ld: /home/yhong/oepl-cc2630-firmware/firmware/oepl_rf_cc2630.c:191:(.text.oepl_rf_init+0x100): undefined reference to `NOROM_RFCDoorbellSendTo'
/usr/lib/gcc/arm-none-eabi/13.2.1/../../../arm-none-eabi/bin/ld: /home/yhong/oepl-cc2630-firmware/firmware/oepl_rf_cc2630.c:199:(.text.oepl_rf_init+0x132): undefined reference to `NOROM_RFCDoorbellSendTo'
/usr/lib/gcc/arm-none-eabi/13.2.1/../../../arm-none-eabi/bin/ld: build/firmware/oepl_rf_cc2630.o: in function `oepl_rf_tx':
/home/yhong/oepl-cc2630-firmware/firmware/oepl_rf_cc2630.c:323:(.text.oepl_rf_tx+0x78): undefined reference to `NOROM_RFCDoorbellSendTo'
/usr/lib/gcc/arm-none-eabi/13.2.1/../../../arm-none-eabi/bin/ld: build/firmware/oepl_rf_cc2630.o: in function `oepl_rf_rx_stop':
/home/yhong/oepl-cc2630-firmware/firmware/oepl_rf_cc2630.c:447:(.text.oepl_rf_rx_stop+0x4): undefined reference to `NOROM_RFCDoorbellSendTo'
/usr/lib/gcc/arm-none-eabi/13.2.1/../../../arm-none-eabi/bin/ld: build/firmware/oepl_rf_cc2630.o: in function `oepl_rf_shutdown':
/home/yhong/oepl-cc2630-firmware/firmware/oepl_rf_cc2630.c:481:(.text.oepl_rf_shutdown+0x4): undefined reference to `NOROM_RFCDoorbellSendTo'
/usr/lib/gcc/arm-none-eabi/13.2.1/../../../arm-none-eabi/bin/ld: /home/yhong/oepl-cc2630-firmware/firmware/oepl_rf_cc2630.c:487:(.text.oepl_rf_shutdown+0x16): undefined reference to `NOROM_RFCSynthPowerDown'
/usr/lib/gcc/arm-none-eabi/13.2.1/../../../arm-none-eabi/bin/ld: build/firmware/oepl_hw_abstraction_cc2630.o: in function `oepl_hw_spi_init':
/home/yhong/oepl-cc2630-firmware/firmware/oepl_hw_abstraction_cc2630.c:49:(.text.oepl_hw_spi_init+0x14): undefined reference to `PRCMPowerDomainStatus'
collect2: error: ld returned 1 exit status
```

However, I was able to finally build successfully after using `tirtos_cc13xx_cc26xx_2_21_01_08/` instead and grabbing  `rf_ieee_cmd.h` and `rf_ieee_mailbox.h` from contiki_ng to fill in the missing header files.  I would love to know the slightly less hacky way of getting to work correctly.  On the plus side, I was able to program the tag using the xds110 off of launchpad board, which saved a lot of money in getting a programmer 😸

**Comment by ratsark** [comment]
Three months late, sorry. You solved this yourself and then fixed it in your
fork, and I never looked.

I went through it properly today. Two things:

**Your `-I$(CC26X0_DIR)` include-path addition looks right** and I'd take it as
a PR.

**Your `SysCtrlAdjustRechargeAfterPowerDown(0)` → `()` change I can't take**, and
the reason is the actual bug here. The driverlib this firmware is built against
declares:

```c
extern void SysCtrlAdjustRechargeAfterPowerDown( uint32_t vddrRechargeMargin );
```

so it takes the argument, and dropping it would break the build for anyone using
that driverlib. Your change is correct *for the older driverlib you were forced
to fall back to* — which is the point: the repo never said which driverlib it
wanted, so you ended up on a different one and the API didn't match. That's a
documentation failure on my side, not a code problem on yours.

You are not the only person who hit it. @chaim3546 independently ran into the
same signature mismatch and wrote it up in a `BUILD.md` on the
`fix/uart-debug-output` branch of their fork, including *why*:
`contiki-os/cc26xxware` is a partial mirror — it omits `rf_ieee_cmd.h` and its
API is a generation older — whereas `contiki-ng/cc2640r2-sdk` is complete and
matches. That's the thing this repo should have said from the start, and it's
what your XDS110 experience deserved instead of a linker error wall.

So the real fix for this issue is to land a pinned, login-free driverlib recipe,
and I'd rather do that than paper over it. I've asked chaim3546 in #2.

In the meantime there's now a release with prebuilt binaries, if you ever want
to skip the toolchain entirely:
https://github.com/ratsark/oepl-cc2630-firmware/releases/tag/v0.32

Nice find on the XDS110 off a LaunchPad, by the way — that's a much cheaper
route than a J-Link and worth documenting. If you're willing to write two lines
about the wiring I'll put it in DEVELOPMENT.md with credit.

See #9 for what's changed since you forked — short version, the tag now gets
about six years on a set of cells instead of about 450 days.

**Comment by knyghtryda** [comment]
@ratsark happy to get you a more detailed setup of how I got the programmer going on the xds110.  I programmed a few and then forgot about it as well :) I'll get some pictures and a writeup so that its useful for anyone else trying it.  I'll also try and get my local setup working again, and rebase against upstream.  I kinda want to make sure everything is still working with all of the tooling fixes.

**Comment by ratsark** [comment]
Pictures and a write-up would be great — the XDS110 route is the cheapest way
into this chip and it isn't documented anywhere I can find.

Two things before you sink time into the rebase.

You're ~45 commits behind and a fair amount moved, so a rebase may be more
painful than it's worth. If you'd rather, point me at the branch and I'll
cherry-pick with your authorship intact.

More importantly: **your `SysCtrlAdjustRechargeAfterPowerDown()` change may
become unnecessary.** @chaim3546 has a `BUILD.md` that pins a specific
driverlib (`contiki-ng/cc2640r2-sdk` rather than the partial
`contiki-os/cc26xxware` mirror), and against that one the call takes its
argument and upstream builds unmodified. I've asked them to send it as a PR. If
it lands first, the right rebase is "drop that commit and follow BUILD.md" —
which would be a smaller diff and one less local patch for you to carry.

Your include-path fix stands either way.

Also worth knowing before you re-test: OTA from the AP works well now, so once
you're on a recent build you can update over the air and skip the programmer
entirely for iteration. A v0.7 tag I had sitting in a drawer since February
took v0.32 over the air this morning in 282 seconds, and the bench tag reported
`OTA-APPLIED sectors=7 retries=0 unverified=0` on the way to v46 this
afternoon.

**Comment by knyghtryda** [comment]
Here's the branch https://github.com/knyghtryda/oepl-cc2630-firmware/tree/latest-sdk.

**Comment by knyghtryda** [comment]
@ratsark PR for xds110 is here #10
